---

# This allows for making the {{ project_name }}_{{ env_name }}.yml vars file optional.
# If this vars file is _not_ included in the role, the variables should be defined
# elsehwere - e.g. in the playbook file
- name: Determine if the project-specific vars file exists
  local_action:
    module: stat
    path: "{{ role_path }}/vars/{{ project_name }}_{{ env_name }}.yml"
  register: project_vars_file

- name: Set-up project-specific environment variables
  include_vars: "{{ project_name }}_{{ env_name }}.yml"
  when: project_vars_file.stat.exists
  no_log: True

- name: Set-up the Capistrano environment
  import_tasks: cap_setup.yml

- name: Set-up the Sidekiq environment
  import_tasks: sidekiq_setup.yml

- name: Set-up the dotenv environment variables file
  import_tasks: dotenv_setup.yml

- name: Set-up the rails application secret key
  import_tasks: rails_secretkey_setup.yml

- name: Set-up the ansible user's environment to run the deploy
  import_tasks: ansible_user_env_setup.yml

- name: Set-up the Apache HTTPD virtual host file
  import_tasks: apache_vhost_setup.yml

- name: Set-up the rails application logrotate configuration
  import_tasks: logrotate_setup.yml

- name: Execute the capistrano deploy process
  import_tasks: capistrano_deploy.yml
